### ISSUE TITLE
Auth issue with latest version

### ISSUE THREAD

**Issue by okjed** [UCSB-PSTAT/base-rstudio#20]
I attempted to use this image in a Kubernetes JupyterHub installation and I'm running into a an auth issue with RStudio. Is this a known issue with current versions?

**Comment by vwbusguy** [comment]
Nope, we're using the current versions of things here in production.  If you don't setup auth in your helm chart, it will spit out a token in the logs when it first starts that you can use to log in.  You can also see where we test token login for each build as well [here](https://github.com/UCSB-PSTAT/base-rstudio/blob/main/Jenkinsfile#L26).

**Comment by okjed** [comment]
First, thanks for such a rapid response! I have to admit I'm fairly new to much of this. I've been running the K8s-based JupyterHub with auth via a helm-based installation for a year, just modifying available images as needed. I was considering using this base and adding pre-loading packages for an upcoming workshop but I must be missing an aspect needed. I'll close this issue but I welcome any helpful guidance.

**Comment by vwbusguy** [comment]
That's exactly how we deploy it.  The [Zero to JupyterHub](https://z2jh.jupyter.org/en/stable/administrator/authentication.html) docs are a particularly helpful reference for setting up JupyterHub.  These images are based on Jupyter upstream images, so the docs there should be 100% compatible with these images.

**Comment by okjed** [comment]
[Zero to JupyterHub](https://z2jh.jupyter.org/en/stable/administrator/authentication.html) is definitely some of the best documentation I often revisit. It's helped me leverage various different auth paths for different deployments. I'll continue to dig into this to see what I'm failing to do - or in the interest of a weekend, I may just fallback to my old method for now.
